# Generated by Django 5.1.1 on 2024-09-28 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('status', '0002_rename_name_statuscredit_description_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('no_installment', models.SmallIntegerField()),
                ('application_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('penalty_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.statuscredit')),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.interestrate')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.credit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.statuspayment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('id_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.credit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_client', 'id_product', 'id_credit'), name='unique_client_credit_product')],
            },
        ),
    ]
