# Generated by Django 5.1.1 on 2024-10-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.client'),
        ),
        migrations.AddField(
            model_name='credit',
            name='products',
            field=models.ManyToManyField(through='credits.ClientCreditProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='clientcreditproduct',
            name='id_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='credits.credit'),
        ),
        migrations.AddField(
            model_name='credit',
            name='interest_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='credits.interestrate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='credits.credit'),
        ),
    ]
