# Generated by Django 5.1.1 on 2024-09-28 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscredit',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='statusgeneral',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='statuspayment',
            old_name='name',
            new_name='description',
        ),
    ]
