# Generated by Django 5.1.1 on 2024-11-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.producttype')),
            ],
        ),
    ]
